### ISSUE TITLE
defaultOptionText missing in index.d.ts

### ISSUE THREAD

**Issue by engineersamuel** [kunyan/react-bootstrap-xeditable#1]
It looks like EditableSelect supports the defaultOptionText prop however that is missing in the interface so the IDE throws an error.  Please update the index.d.ts.

(Also if you give me permissions and add a contributor guide to the Readme and I could do it)

**Comment by kunyan** [comment]
Fixed in https://github.com/kunyan/react-bootstrap-xeditable/commit/bb6bfdfaa014df11df86786c8798b439c375d667
