### ISSUE TITLE
typescript error in importing react

### ISSUE THREAD

**Issue by ryangcode** [kunyan/react-bootstrap-xeditable#14]
Hi,
Thanks a lot for your work.
 wonder if you could do a npm publish with the fix for typescript integration.
import React from 'react';
should be import * as React from 'react';

in the *.d.ts.

Many thanks.

**Comment by ryangcode** [comment]
I am currently blocked by this one. apprecriate if you could publish at your earliest convenience.

Many Thanks.

**Comment by kunyan** [comment]
New version published to NPM
