### ISSUE TITLE
Cannot control component

### ISSUE THREAD

**Issue by aberonni** [kunyan/react-bootstrap-xeditable#6]
**Expected behavior**
When I set the value on the component it should always use the provided value - just like all [controlled components](https://facebook.github.io/react/docs/forms.html#controlled-components).

**Actual behavior**
The component only accepts the initial value. If you update state/props in the `onUpdate` handler, those updates are not reflected onto the component.

I've created a fork of the demo pen to demonstrate my problem:
http://codepen.io/anon/pen/WjgVdZ

**Comment by aberonni** [comment]
I can see that this issue (at least for the text field) is caused on line 52 of [this file](https://github.com/kunyan/react-bootstrap-xeditable/blob/master/src/EditableTextField.js#L52).

You are always using the internal state.value when I think you should be using props.value always.

**Comment by aberonni** [comment]
Actually reverting to v0.2.7 works as expected so I think this is a regression.

**Comment by aberonni** [comment]
Thank you, any chance of a release on npm?

**Comment by hellofantastic** [comment]
Will this solve the issue of changing an editable textfields value from its parent component state?
ie I have a links of links, if you click on one it should update an editable textfield

**Comment by aberonni** [comment]
@hellofantastic I believe that it would, but to use the fix properly we need to wait for a new version of the module on npm.
